name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install API deps
        working-directory: api
        run: |
          npm ci

      - name: Build API (typecheck)
        working-directory: api
        run: |
          npx tsc -p tsconfig.json --noEmit

      - name: Install Web deps
        working-directory: web
        run: |
          npm ci

      - name: Build Web
        working-directory: web
        env:
          API_BASE_URL: http://localhost:4000
          NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
        run: |
          npm run build --if-present

      - name: Install ETL deps
        working-directory: etl
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run ETL unit tests
        working-directory: etl
        run: |
          pytest -q
