name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install API deps
        working-directory: api
        run: |
          npm ci
          npm run build

      - name: Install Web deps
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ETL deps
        working-directory: etl
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          python -c "import ohio_fit_etl; print('etl ok')"
